python-interpreter-path = ".venv_new/Scripts/python.exe"
search-path = ["Task1_Sentiment_Chatbot", "Task2_Medical_QA_Chatbot", "Task3_ArXiv_CS_Chatbot"]

[errors]
untyped-import = "ignore"
bad-argument-type = "ignore"
